Generate CMR limited pools
NCMulder/MTG_Scripts pull request #16
Opened 2020-11-06 22:55 UTC by JorimWal

Implements issue #15, generating limited packs from the new set Commander Legends

2020-11-07 15:40 UTC, Marcanius requested changes
I added 2 things that should change this pull request quite a bit.

2020-11-07 15:40 UTC, Marcanius commented on Scryfall Tools/limited_pools.py
> +        if(foil_rng == 119):
Python tries to avoid unnecessary brackets around statements:

```suggestion
        if foil_rng == 119:
```

2020-11-07 15:40 UTC, Marcanius commented on Scryfall Tools/limited_pools.py
> +            rarity = 'c'
For a weighted choice from a list, you can try the random.choices() method.

Examples: [https://pynative.com/python-weighted-random-choices-with-probability/](url)

```suggestion
        # Get 1 foil
        # Randomly determine rarity of foil
        rarity = random.choices(
            [m', 'r', 'u', 'c'], 
            [1, 8, 23, 88]
        )
```

2020-11-08 13:03 UTC, NCMulder requested changes

2020-11-08 13:03 UTC, NCMulder commented on Scryfall Tools/limited_pools.py
> +        if(rarity == 'm'):
Remove brackets

2020-11-08 13:03 UTC, NCMulder commented on Scryfall Tools/limited_pools.py
> +        if('Legendary' in card['type_line']):
Remove brackets

2020-11-08 13:03 UTC, NCMulder commented on Scryfall Tools/limited_pools.py
> +            if(etched_foil_rng == 1):
Remove brackets

2020-11-08 13:03 UTC, NCMulder commented on Scryfall Tools/limited_pools.py
> +        pack += [st.get_random_card(f'set:{set_code} t:legendary is:booster r:{rarity_2}')]
Make sure no duplicate legendaries are pulled

2020-11-08 13:25 UTC, NCMulder approved these changes

2020-11-08 13:44 UTC, Marcanius approved these changes

2020-11-08 13:44 UTC, merged